# --- START OF FILE netlify.toml ---

[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/bands/:slug"
  to = "/band-profile.html"
  status = 200

# --- END OF FILE netlify.toml ---
