# --- START OF FILE netlify.toml ---

[build]
  publish = "public"
  functions = "netlify/functions"

# Increase the timeout for all functions to 20 seconds.
# This gives a sleeping serverless database enough time to wake up.
[functions]
  timeout = 20
