# --- START OF FILE netlify.toml ---

[build]
  functions = "netlify/functions"
  publish = "public"

# RULE 1: API calls must always work.
# This rule proxies any /api/ request to your Netlify functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# RULE 2: Band Profile Public Pages.
# This routes all public band pages to the correct HTML file.
[[redirects]]
  from = "/bands/*"
  to = "/band-profile.html"
  status = 200

# RULE 3: Main Homepage Rule.
# This ensures that visiting the root of your site serves the main index page.
# This is a fallback that's good practice to have.
[[redirects]]
  from = "/"
  to = "/proanthem_index.html"
  status = 200

# --- END OF FILE netlify.toml ---
