# Netlify Configuration File for ProAnthem

[build]
  functions = "netlify/functions/"
  publish = "public/"

# This rule ensures that API calls are correctly proxied to your serverless functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This is the main rule for the entire ProAnthem site.
# It serves the proanthem_index.html for any request to the root.
[[redirects]]
  from = "/"
  to = "/proanthem_index.html"
  status = 200
  force = true
