[build]
  functions = "netlify/functions"
  publish = "public"

# RULE 1: API calls must always work.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# RULE 2: Developer Access.
# Passthrough for developers with the secret key.
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
  conditions = { "dev" = "true" }

# RULE 3: Allow Assets to be Served.
# NEW RULE! This is the fix.
# This rule tells Netlify to serve any files in the /assets, /css, or /js folders normally.
# It MUST come before the final catch-all rule.
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

# RULE 4: The "Under Construction" Catch-All.
# If a request is not an API call, not from a dev, and not for an asset,
# THEN AND ONLY THEN serve the construction page.
[[redirects]]
  from = "/*"
  to = "/construction.html"
  status = 200
  force = true
