# This is the main configuration file for your Netlify site.

[build]
  # This tells Netlify where your serverless functions are located.
  functions = "netlify/functions"
  # This tells Netlify which folder to publish as the live site.
  publish = "public"

[[redirects]]
  # This rule handles all your API calls. Any request to /api/*
  # will be forwarded to the corresponding Netlify function.
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # --- THIS IS THE FIX ---
  # This rule handles the public band profile pages.
  # Any request to /bands/some-slug...
  from = "/bands/:slug"
  # ...will be rewritten to serve the band-profile.html file.
  to = "/band-profile.html"
  # Status 200 means it's a rewrite, not a redirect. The URL in the browser bar stays the same.
  status = 200
