[build]
  functions = "netlify/functions"
  publish = "public"

# Redirects for your API functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# NEW: The "Under Construction" Redirect Rules
# This rule will redirect ALL traffic to the construction page,
# EXCEPT for requests that have a special "developer" query parameter.
[[redirects]]
  from = "/*"
  to = "/construction.html"
  status = 302 # Temporary redirect
  conditions = { "dev" = "!true" } # The magic condition

# This rule makes it so that if you go to the root of the site with the
# special parameter, it correctly serves the main index page.
[[redirects]]
  from = "/"
  to = "/proanthem_index.html"
  status = 200
  query = { "dev" = "true" }
