# This is the main configuration file for your Netlify site.

[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  # --- FIX: Update the specific rule for the renamed function ---
  from = "/api/bandpage/*"
  to = "/.netlify/functions/bandpage"
  status = 200

[[redirects]]
  # This is the generic rule for all other API calls.
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # This rule for the frontend remains correct.
  from = "/bands/:slug"
  to = "/band-profile.html"
  status = 200
