# --- START OF FILE netlify.toml ---

# This is a rewrite rule. It tells Netlify to serve the band-profile.html file
# for any request to a path starting with /bands/, while keeping the original URL
# in the browser's address bar. This allows the JavaScript to get the band's slug.
[[redirects]]
  from = "/bands/:slug"
  to = "/band-profile.html"
  status = 200

# --- END OF FILE netlify.toml ---
