[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This rule makes proanthem_index.html the homepage
[[redirects]]
  from = "/"
  to = "/proanthem_index.html"
  status = 200
